import { z } from "zod";
import { callLLM } from "../openRouterProvider";
import type { SearchSessionDetail, RankedPaper } from "./types";

const ORCHESTRATOR_MODEL =
  process.env.OPENROUTER_PLANNER_MODEL ?? "google/gemini-2.5-flash-lite";

const sidebarActionSchema = z.object({
  actionType: z.enum([
    "answer_current_results",
    "refine_current_canvas",
    "focused_retrieval_expansion",
    "clarification_prompt",
    "exhaustive_intent_transparency",
  ]),
  // assistantReply is now OPTIONAL - will be generated by synthesizer for evidence-based answers
  assistantReply: z.string().optional(),
  // For evidence-based answers, we'll generate synthesis instead of using this
  userIntent: z.object({
    mainQuestion: z.string(),
    needsNewEvidence: z.boolean(),
    comparisonTarget: z.string().nullable(),
    specificOutcome: z.string().nullable(),
  }),
  refinedQuery: z.string().nullable(),
  reuseCurrentPapers: z.boolean(),
  filters: z.object({
    population: z.enum(["human", "animal", "in_vitro"]).nullable(),
    studyDesign: z.enum(["meta_analysis", "systematic_review", "rct", "cohort", "cross_sectional"]).nullable(),
    evidenceBuckets: z.array(z.enum(["strongest", "human_observational", "mechanistic", "background", "conflicting"])).max(3),
    keywordFocus: z.array(z.string()).max(4),
  }),
  focusSummary: z.string(),
  focusBadges: z.array(z.string()).max(5),
  retrievalMode: z.enum(["reused_current_papers", "focused_retrieval"]).nullable(),
});

export type SidebarAction = z.infer<typeof sidebarActionSchema>;

const SIDEBAR_SYSTEM_PROMPT = `You are Clarity's investigation orchestrator. Your job is to understand what the user is REALLY asking and decide how to advance their investigation.

CRITICAL: You are NOT writing the final answer. You are deciding the best next step.

═══ UNDERSTAND THE USER ═══

People don't always ask precisely what they want to know. Your job is to extract:
- mainQuestion: What are they really asking? Distill to one sharp sentence. Not their literal words — their actual investigation goal.
- needsNewEvidence: Do the current papers adequately answer this, or do we need new retrieval?
- comparisonTarget: Are they comparing X vs Y? Be specific about the comparator.
- specificOutcome: What specific outcome do they care about? (e.g., not "health" but "insulin sensitivity" or "adherence")

═══ DECIDE THE NEXT STEP ═══

Choose exactly one action:

1. answer_current_results — The current papers CAN answer this question. No new retrieval needed. The synthesizer will interpret the existing evidence with this specific angle in mind.

2. refine_current_canvas — Narrow the current view (e.g., "show me only RCTs" or "focus on human studies"). Same papers, different filter.

3. focused_retrieval_expansion — We need NEW papers to answer this properly. The user is asking about something the current set doesn't cover: a comparison, a specific outcome, a different population, a different intervention.

4. clarification_prompt — The user's intent is genuinely unclear, or their query is too broad to narrow usefully. Ask ONE specific clarifying question that would unlock the investigation.

5. exhaustive_intent_transparency — The user asked for exhaustive coverage ("find all papers," "comprehensive search"). Be honest that this is a curated starting set, not a complete literature sweep.

═══ DECISION GUIDELINES ═══

- Comparison questions ("is X better than Y?") → focused_retrieval_expansion (single-intervention retrieval rarely answers comparisons well)
- "What about [specific outcome]?" → focused_retrieval_expansion if that outcome isn't well covered in current papers
- "Why the contradiction?" / "What did this paper find?" → answer_current_results
- "Show me only [study type / population]" → refine_current_canvas
- Vague/broad → clarification_prompt (don't guess — ask)
- Personal context framing ("I'm tired all the time," "for someone my age") → treat as a change in exploration angle, possibly clarification if too broad

═══ IMPORTANT ═══

Set assistantReply ONLY for clarification_prompt or exhaustive_intent_transparency. For answer_current_results, refine_current_canvas, and focused_retrieval_expansion, leave assistantReply empty/null — the synthesizer will generate the actual answer from the evidence.

Return strict JSON.`;

function normalizeText(value: string): string {
  return value.toLowerCase().replace(/\s+/g, " ").trim();
}

function looksLikeCurrentResultsQuestion(userInput: string): boolean {
  const normalized = normalizeText(userInput);
  return /^(what does|what do|are these|is this|why is|why are|how strong|how much|does this mean)/.test(
    normalized,
  );
}

function looksLikePersonalContextRefinement(userInput: string): boolean {
  const normalized = normalizeText(userInput);
  const hasFirstPerson =
    /\b(i'm|i am|i feel|i get|i have|for me|my)\b/.test(normalized);
  const hasSymptomContext =
    /\b(tired|fatigue|fatigued|sleepy|sleep badly|sleep poorly|exhausted|low energy|brain fog|focus|concentration|wired|anxious|stressed)\b/.test(
      normalized,
    );

  return hasFirstPerson && hasSymptomContext;
}

function looksLikeExplicitRefinement(userInput: string): boolean {
  const normalized = normalizeText(userInput);
  return /^(only|focus on|narrow to|limit to|show me stronger evidence|human rcts only)/.test(
    normalized,
  ) || /\bnon[- ]pharmaceutical only\b/.test(normalized);
}

function looksLikeExhaustiveIntent(userInput: string): boolean {
  const normalized = normalizeText(userInput);
  return /\b(find all papers|show all studies|everything on this|literature review|comprehensive search|all papers|all studies)\b/.test(
    normalized,
  );
}

function looksLikePrecisionGapQuestion(userInput: string): boolean {
  const normalized = normalizeText(userInput);
  return /\b(short-term|long-term|duration|follow-up|protocol|dosage|dose|subgroup|side effects|adverse effects|harms|safety)\b/.test(
    normalized,
  );
}

function looksLikeBroadTopicFragment(session: SearchSessionDetail, userInput: string): boolean {
  const normalized = normalizeText(userInput);
  if (normalized.includes("?")) return false;
  if (normalized.split(" ").length > 4) return false;
  if (/^(what about|show me|only|focus on|compare|is this|are these|why is|why are)/.test(normalized)) {
    return false;
  }

  const sessionTerms = new Set(
    [...session.plan.entities, ...session.query.split(/\s+/)]
      .map((term) => term.toLowerCase().replace(/[^a-z0-9-]/g, ""))
      .filter((term) => term.length > 3),
  );

  const overlap = normalized
    .split(/\s+/)
    .map((term) => term.replace(/[^a-z0-9-]/g, ""))
    .filter((term) => term.length > 3)
    .some((term) => sessionTerms.has(term));

  return !overlap;
}

function buildPersonalContextClarification(userInput: string): string {
  const normalized = normalizeText(userInput);

  if (/\b(tired|fatigue|fatigued|low energy|exhausted)\b/.test(normalized)) {
    return "Tiredness points in a different direction than a generic brain-fog question. Are you mainly trying to understand sleep-related fatigue, low energy, or concentration problems despite adequate sleep?";
  }

  if (/\b(sleep badly|sleep poorly|sleepy)\b/.test(normalized)) {
    return "Poor sleep changes the exploration angle here. Are you trying to understand sleep deprivation effects, sleep-quality effects, or interventions that might help despite poor sleep?";
  }

  return "That changes the exploration angle. Are you mainly trying to understand sleep, fatigue, or a more specific symptom pattern?";
}

function buildClarificationReply(session: SearchSessionDetail, userInput: string): string {
  if (looksLikePersonalContextRefinement(userInput)) {
    return buildPersonalContextClarification(userInput);
  }

  const normalized = normalizeText(userInput);
  if (normalized.includes("depression interventions")) {
    return "Depression interventions is still broad. Are you more interested in therapy approaches, sleep or exercise, treatment-resistant depression, or medication comparisons?";
  }

  return "I need one more detail before narrowing this cleanly. Which direction matters most here?";
}

function buildExhaustiveTransparencyReply(): string {
  return "This canvas is a curated starting set, not an exhaustive literature sweep. A broader all-papers mode is not implemented yet, so I should not present the current set as comprehensive.";
}

function buildPrecisionGapReply(session: SearchSessionDetail, userInput: string): string {
  const normalized = normalizeText(userInput);

  if (/\b(short-term|long-term|duration|follow-up)\b/.test(normalized)) {
    return "The current abstracts do not make that clear enough. This canvas gives a directional read on the evidence, but not a reliable split between short-term and longer-term outcomes.";
  }

  if (/\b(protocol|dosage|dose)\b/.test(normalized)) {
    return "The current abstracts do not make that clear enough. This set is better for the overall evidence shape than for exact protocol or dosage details.";
  }

  if (/\b(subgroup)\b/.test(normalized)) {
    return "The current abstracts do not make that clear enough. They do not give a reliable subgroup read from the current canvas alone.";
  }

  if (/\b(side effects|adverse effects|harms|safety)\b/.test(normalized)) {
    return "The current abstracts do not make that clear enough. Safety and adverse-effect detail are not consistently visible in the current abstracts.";
  }

  return `The current abstracts do not make that clear enough. This canvas is better for the overall evidence shape around ${session.query} than for that level of detail.`;
}

function buildExplicitRefinementReply(session: SearchSessionDetail, userInput: string): {
  reply: string;
  refinedQuery: string;
  focusSummary: string;
  focusBadges: string[];
} {
  const normalized = normalizeText(userInput);

  if (normalized.includes("non-pharmaceutical")) {
    return {
      reply: "I narrowed this to non-pharmaceutical interventions and refreshed the canvas around that.",
      refinedQuery: `${session.query} non-pharmaceutical interventions therapy exercise sleep mindfulness CBT psychotherapy lifestyle`,
      focusSummary: "Narrowed toward non-pharmaceutical interventions within the current exploration.",
      focusBadges: ["non-pharmaceutical", "behavioral", "therapy-first"],
    };
  }

  if (normalized.includes("human rct")) {
    return {
      reply: "I narrowed this toward human randomized evidence and updated the canvas accordingly.",
      refinedQuery: `${session.query} human randomized controlled trial`,
      focusSummary: "Narrowed toward human randomized evidence within the current exploration.",
      focusBadges: ["human evidence first", "RCT-focused"],
    };
  }

  return {
    reply: "I narrowed the canvas around that constraint and refreshed the evidence accordingly.",
    refinedQuery: `${session.query} ${userInput.trim()}`,
    focusSummary: `Refined the canvas around ${userInput.trim()}.`,
    focusBadges: [userInput.trim()].slice(0, 1),
  };
}

function normalizeAction(
  session: SearchSessionDetail,
  userInput: string,
  action: SidebarAction,
): SidebarAction {
  if (/\bnon[- ]pharmaceutical only\b/.test(normalizeText(userInput))) {
    const refinement = buildExplicitRefinementReply(session, userInput);
    return {
      ...action,
      actionType: "refine_current_canvas",
      assistantReply: refinement.reply,
      refinedQuery: refinement.refinedQuery,
      reuseCurrentPapers: false,
      retrievalMode: "focused_retrieval",
      focusSummary: refinement.focusSummary,
      focusBadges: refinement.focusBadges,
    };
  }

  if (looksLikeExhaustiveIntent(userInput)) {
    return {
      ...action,
      actionType: "exhaustive_intent_transparency",
      assistantReply: buildExhaustiveTransparencyReply(),
      refinedQuery: null,
      reuseCurrentPapers: false,
      retrievalMode: null,
      focusSummary: session.focusState.summary,
      focusBadges: [...session.focusState.badges.slice(0, 4), "curated starting set"].slice(0, 5),
    };
  }

  if (
    action.actionType === "answer_current_results" &&
    looksLikePersonalContextRefinement(userInput)
  ) {
    return {
      ...action,
      actionType: "clarification_prompt",
      assistantReply: buildClarificationReply(session, userInput),
      refinedQuery: null,
      reuseCurrentPapers: false,
      retrievalMode: null,
      focusSummary: session.focusState.summary,
      focusBadges: session.focusState.badges,
    };
  }

  if (
    action.actionType === "clarification_prompt" &&
    looksLikeCurrentResultsQuestion(userInput)
  ) {
    return {
      ...action,
      actionType: "answer_current_results",
      reuseCurrentPapers: false,
      retrievalMode: null,
    };
  }

  if (
    (action.actionType === "clarification_prompt" ||
      action.actionType === "answer_current_results") &&
    looksLikeExplicitRefinement(userInput)
  ) {
    const refinement = buildExplicitRefinementReply(session, userInput);
    return {
      ...action,
      actionType: "refine_current_canvas",
      // NO assistantReply - will be synthesized from evidence after retrieval
      refinedQuery: refinement.refinedQuery,
      reuseCurrentPapers: false,
      retrievalMode: "focused_retrieval",
      focusSummary: refinement.focusSummary,
      focusBadges: refinement.focusBadges,
    };
  }

  if (
    action.actionType === "refine_current_canvas" &&
    looksLikeBroadTopicFragment(session, userInput)
  ) {
    return {
      ...action,
      actionType: "clarification_prompt",
      assistantReply: buildClarificationReply(session, userInput), // OK: clarification uses orchestrator reply
      reuseCurrentPapers: false,
      retrievalMode: null,
    };
  }

  // Removed: Old pattern of setting generic assistantReply before retrieval
  // Now we let the synthesizer generate the answer AFTER retrieval
  // The synthesizer will explain what was retrieved and what changed

  if (
    action.actionType === "clarification_prompt" &&
    /(^|\b)(i will|i narrowed|i filtered|i updated|refreshed the canvas|updated the canvas)(\b|$)/i.test(
      action.assistantReply,
    )
  ) {
    return {
      ...action,
      assistantReply: buildClarificationReply(session, userInput),
      retrievalMode: null,
    };
  }

  if (
    action.actionType === "answer_current_results" &&
    looksLikePrecisionGapQuestion(userInput)
  ) {
    // Precision gap questions should still be answered from current evidence
    // but the synthesizer will handle explaining the limitations
    return {
      ...action,
      retrievalMode: null,
    };
  }

  if (
    action.actionType === "answer_current_results" ||
    action.actionType === "clarification_prompt" ||
    action.actionType === "exhaustive_intent_transparency"
  ) {
    return {
      ...action,
      retrievalMode: null,
    };
  }

  return action;
}

function summarizePapers(papers: RankedPaper[]): string {
  return papers.slice(0, 6).map((paper, index) => [
    `Paper ${index + 1}: ${paper.title}`,
    `Study design: ${paper.studyDesign} | Population: ${paper.populationType} | Bucket: ${paper.evidenceBucket}`,
    `Summary: ${paper.plainSummary}`,
  ].join("\n")).join("\n\n");
}

export async function orchestrateSidebarInput(
  session: SearchSessionDetail,
  userInput: string,
): Promise<SidebarAction> {
  const userMessage = [
    `SIDEBAR INPUT: ${userInput}`,
    `CURRENT QUERY: ${session.query}`,
    `CURRENT FOCUS SUMMARY: ${session.focusState.summary}`,
    `CURRENT FOCUS BADGES: ${session.focusState.badges.join(", ")}`,
    `CURRENT INTENT: ${session.plan.intentType}`,
    `CURRENT ENTITIES: ${session.plan.entities.join(", ")}`,
    `CURRENT FIRST READ: ${session.synthesisText}`,
    `CURRENT EVIDENCE SNAPSHOT: meta=${session.evidenceSnapshot.metaAnalyses}, rcts=${session.evidenceSnapshot.rcts}, human_observational=${session.evidenceSnapshot.humanObservational}, mechanistic=${session.evidenceSnapshot.mechanistic}, conflicting=${session.evidenceSnapshot.conflicting}`,
    `CURRENT PAPERS:`,
    summarizePapers(session.papers),
  ].join("\n\n");

  const raw = await callLLM(
    SIDEBAR_SYSTEM_PROMPT,
    userMessage,
    sidebarActionSchema,
    { model: ORCHESTRATOR_MODEL, temperature: 0.1, timeoutMs: 25_000 },
  );

  const data = typeof raw === "string" ? JSON.parse(raw) : raw;
  const parsed = sidebarActionSchema.parse(data);
  return normalizeAction(session, userInput, parsed);
}
